nelmio_api_doc:
    documentation:
        info:
            title: Content API
            description: Handsome API to work with blocks
            version: 1.0.0
        produces:
          - application/vnd.api+json
        consumes:
          - application/json
