restaurants:
  type:     rest
  resource: App\Controller\RestaurantController

activities:
  type:     rest
  resource: App\Controller\ActivityController

products:
  type:     rest
  resource: App\Controller\ProductController

search:
  type:     rest
  resource: App\Controller\SearchController

closestRestaurants:
  type:     rest
  resource: App\Controller\ClosestRestaurantController
